apiVersion: v2
appVersion: 1.26.2
description: A Helm chart to run Azure CSI driver for Azure Disks.
icon: https://s.giantswarm.io/app-icons/azure/1/dark.svg
home: https://github.com/giantswarm/azuredisk-csi-driver-app
name: azuredisk-csi-driver-app
version: [[ .Version ]]
restrictions:
  clusterSingleton: true
  fixedNamespace: kube-system
  gpuInstances: false
  compatibleProviders: [azure]
