apiVersion: v2
appVersion: 0.0.1-dev
description: A Helm chart to run Azure CSI driver for Azure Disks.
icon: https://s.giantswarm.io/app-icons/azure/1/dark.svg
home: https://github.com/giantswarm/azuredisk-csi-driver-app
name: azuredisk-csi-driver-app
version: 0.0.1-dev
restrictions:
  clusterSingleton: true
  fixedNamespace: kube-system
  gpuInstances: false
  compatibleProviders: [azure]
annotations:
  application.giantswarm.io/team: phoenix
  config.giantswarm.io/version: 1.x.x
  ui.giantswarm.io/logo: https://s.giantswarm.io/app-icons/azure/1/dark.svg
