# Default values for name: k8s-dns-node-cache-chart
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

name: azuredisk-csi
serviceType: managed

image:
  baseRepo: quay.io/giantswarm/
  azuredisk:
    repository: azuredisk-csi
    tag: v1.26.2
    pullPolicy: IfNotPresent
  csiProvisioner:
    repository: csi-provisioner
    tag: v3.3.0
    pullPolicy: IfNotPresent
  csiAttacher:
    repository: csi-attacher
    tag: v4.0.0
    pullPolicy: IfNotPresent
  csiResizer:
    repository: csi-resizer
    tag: v1.6.0
    pullPolicy: IfNotPresent
  livenessProbe:
    repository: livenessprobe
    tag: v2.8.0
    pullPolicy: IfNotPresent
  nodeDriverRegistrar:
    repository: csi-node-driver-registrar
    tag: v2.6.2
    pullPolicy: IfNotPresent

serviceAccount:
  create: true
  controller: csi-azuredisk-controller-sa
  node: csi-azuredisk-node-sa
  snapshotController: csi-snapshot-controller-sa

rbac:
  create: true
  name: azuredisk

controller:
  name: csi-azuredisk-controller
  cloudConfigSecretName: azure-cloud-provider
  cloudConfigSecretNamespace: kube-system
  allowEmptyCloudConfig: false
  replicas: 2
  metricsPort: 29604
  livenessProbe:
    healthPort: 29602
  runOnMaster: false
  masterNodeSelector:
    "kubernetes.io/role": master
  disableAvailabilitySetNodes: true
  provisionerWorkerThreads: 100
  attacherWorkerThreads: 500
  logLevel: 5
  tolerations:
    - key: "node-role.kubernetes.io/master"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "node-role.kubernetes.io/controlplane"
      operator: "Exists"
      effect: "NoSchedule"
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
  hostNetwork: true
  podLabels: {}
  verticalPodAutoscaler:
    enabled: true
  resources:
    csiProvisioner:
      limits:
        memory: 500Mi
      requests:
        cpu: 10m
        memory: 20Mi
    csiAttacher:
      limits:
        memory: 500Mi
      requests:
        cpu: 10m
        memory: 20Mi
    csiResizer:
      limits:
        memory: 500Mi
      requests:
        cpu: 10m
        memory: 20Mi
    csiSnapshotter:
      limits:
        memory: 100Mi
      requests:
        cpu: 10m
        memory: 20Mi
    livenessProbe:
      limits:
        memory: 100Mi
      requests:
        cpu: 10m
        memory: 20Mi
    azuredisk:
      limits:
        memory: 500Mi
      requests:
        cpu: 10m
        memory: 20Mi

node:
  cloudConfigSecretName: azure-cloud-provider
  cloudConfigSecretNamespace: kube-system
  allowEmptyCloudConfig: true
  maxUnavailable: 1
  metricsPort: 29605
  logLevel: 5
  livenessProbe:
    healthPort: 29603

snapshot:
  enabled: true
  name: csi-snapshot-controller
  image:
    csiSnapshotter:
      repository: csi-snapshotter
      tag: v5.0.1
      pullPolicy: IfNotPresent
    csiSnapshotController:
      repository: snapshot-controller
      tag: v5.0.1
      pullPolicy: IfNotPresent
  verticalPodAutoscaler:
    enabled: true
  snapshotController:
    name: csi-snapshot-controller
    replicas: 2
    podLabels: {}
    resources:
      limits:
        memory: 100Mi
      requests:
        cpu: 10m
        memory: 20Mi

feature:
  enableFSGroupPolicy: true

driver:
  name: disk.csi.azure.com
  # maximum number of attachable volumes per node,
  # maximum number is defined according to node instance type by default(-1)
  volumeAttachLimit: -1
  customUserAgent: ""
  userAgentSuffix: "giantswarm"

linux:
  enabled: true
  dsName: csi-azuredisk-node
  azure_credential_file: /etc/kubernetes/config/azure.yaml
  kubelet: /var/lib/kubelet
  enablePerfOptimization: true
  tolerations:
    - operator: "Exists"
  hostNetwork: true
  podLabels: {}
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: type
              operator: NotIn
              values:
                - virtual-kubelet
  verticalPodAutoscaler:
    enabled: true
  resources:
    livenessProbe:
      limits:
        memory: 100Mi
      requests:
        cpu: 10m
        memory: 20Mi
    nodeDriverRegistrar:
      limits:
        memory: 100Mi
      requests:
        cpu: 10m
        memory: 20Mi
    azuredisk:
      limits:
        memory: 200Mi
      requests:
        cpu: 10m
        memory: 20Mi

cloud: AzurePublicCloud

# set the HTTP_PROXY, HTTPS_PROXY and NO_PROXY variable
proxy:
  noProxy:
  http:
  https:
cluster:
  # is getting overwritten by the top level proxy if set
  # These values are generated via cluster-apps-operator
  proxy:
    noProxy:
    http:
    https:

test:
  image:
    name: giantswarm/alpine-testing
    tag: 0.1.1

podSecurityContext:
  seccompProfile:
    type: RuntimeDefault

# Add seccomp to container security context
securityContext:
  default:
    allowPrivilegeEscalation: false
    seccompProfile:
      type: RuntimeDefault
    capabilities:
      drop:
      - ALL
  node:
    seccompProfile:
      type: RuntimeDefault

global:
  podSecurityStandart:
    enforced: false
