version: 2.1

orbs:
  architect: giantswarm/architect@5.11.4

jobs:
  unit-tests:
    executor: architect/architect
    steps:
      - checkout
      - run:
          name: Run unit tests
          command: CGO_ENABLED=0 make test-unit

workflows:
  package-and-push-chart-on-tag:
    jobs:
      - architect/go-build:
          context: architect
          name: go-build
          binary: azuredisk-csi-driver
          resource_class: xlarge
          filters:
            tags:
              only: /^v.*/

      - unit-tests:
          requires:
            - go-build
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-registries:
          context: architect
          name: push-to-registries
          requires:
            - unit-tests
          filters:
            tags:
              only: /^v.*/
            branches:
              only: /.*/

      - architect/push-to-app-catalog:
          context: architect
          name: push-to-control-plane-app-catalog
          executor: app-build-suite
          app_catalog: control-plane-catalog
          app_catalog_test: control-plane-test-catalog
          chart: azuredisk-csi-driver-app
          abs_configmap: ".abs/control-plane/main.yaml"
          requires:
            - push-to-registries
          filters:
            tags:
              only: /^v.*/
            branches:
              only: /.*/

      - architect/push-to-app-catalog:
          context: architect
          name: push-to-default-app-catalog
          executor: app-build-suite
          app_catalog: default-catalog
          app_catalog_test: default-test-catalog
          chart: azuredisk-csi-driver-app
          abs_configmap: ".abs/default/main.yaml"
          requires:
            - push-to-registries
          filters:
            tags:
              only: /^v.*/
            branches:
              only: /.*/ 
