version: 2.1

orbs:
  architect: giantswarm/architect@5.11.4

workflows:
  build:
    jobs:
      - architect/push-to-app-catalog:
          context: architect
          name: push-to-control-plane-catalog
          executor: app-build-suite
          app_catalog: control-plane-catalog
          app_catalog_test: control-plane-test-catalog
          chart: azuredisk-csi-driver-app
          abs_configmap: .abs/control-plane/main.yaml
          filters:
            # Trigger job on both PRs and tags
            tags:
              only: /^v.*/
            branches:
              only: /.*/

      - architect/push-to-app-catalog:
          context: architect
          name: push-to-default-catalog
          executor: app-build-suite
          app_catalog: default-catalog
          app_catalog_test: default-test-catalog
          chart: azuredisk-csi-driver-app
          abs_configmap: .abs/default/main.yaml
          requires:
            - push-to-control-plane-catalog
          filters:
            # Trigger job on both PRs and tags
            tags:
              only: /^v.*/
            branches:
              only: /.*/ 
