version: 2.1

orbs:
  architect: giantswarm/architect@5.11.4

workflows:
  package-and-push-chart-on-tag:
    jobs:
      - architect/push-to-app-catalog:
          context: architect
          name: push-to-control-plane-catalog
          executor: app-build-suite
          app_catalog: control-plane-catalog
          app_catalog_test: control-plane-test-catalog
          chart: azuredisk-csi-driver-app
          abs_configmap: .abs/control-plane/main.yaml
          filters:
            # Trigger job on git tag.
            tags:
              only: /^v.*/
            branches:
              ignore:
                - main
                - master

      - architect/push-to-app-catalog:
          context: architect
          name: push-to-default-catalog
          executor: app-build-suite
          app_catalog: default-catalog
          app_catalog_test: default-test-catalog
          chart: azuredisk-csi-driver-app
          abs_configmap: .abs/default/main.yaml
          requires:
            - push-to-control-plane-catalog
          filters:
            # Trigger job on git tag.
            tags:
              only: /^v.*/
            branches:
              ignore:
                - main
                - master
