version: 2.1

orbs:
  architect: giantswarm/architect@5.11.4

workflows:
  build:
    jobs:
      - architect/push-to-app-catalog:
          context: architect
          name: push-to-app-catalog
          executor: app-build-suite
          app_catalog: control-plane-catalog
          app_catalog_test: control-plane-test-catalog
          chart: azuredisk-csi-driver-app
          abs_configmap: .abs/control-plane/main.yaml
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore:
              - main
              - master
