version: 2.1
orbs:
  architect: giantswarm/architect@4.13.0

workflows:
  version: 2
  build:
    jobs:
      - architect/push-to-app-catalog:
          context: architect
          name: "push-to-control-plane-app-catalog"
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "azure-cloud-controller-manager-app"
          filters:
            # Trigger the job also on git tag.
            tags:
              only: /^v.*/

      - architect/integration-test:
          context: architect
          name: "basic-integration-test"
          test-dir: "integration/test/basic"
          install-app-platform: true
          filters:
            # Do not trigger the job on merge to master.
            branches:
              ignore:
                - master
          requires:
            - push-to-control-plane-app-catalog

