{{- if .Values.linux.enabled}}
{{- $proxy := deepCopy .Values.cluster.proxy |  mustMerge .Values.proxy }}
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: {{ .Values.linux.dsName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.linux.dsName }}
    app.kubernetes.io/component: "azurediskNode"
{{ include "azuredisk.labels" . | indent 4 }}
spec:
  updateStrategy:
    rollingUpdate:
      maxUnavailable: {{ .Values.node.maxUnavailable }}
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{ .Values.linux.dsName }}
  template:
    metadata:
      labels:
{{ include "azuredisk.labels" . | indent 8 }}
        app: {{ .Values.linux.dsName }}
{{- with .Values.linux.podLabels }}
{{ toYaml . | indent 8 }}
{{- end }}
    spec:
      hostNetwork: {{ .Values.linux.hostNetwork }}
      dnsPolicy: Default
      serviceAccountName: {{ .Values.serviceAccount.node }}
      securityContext:
        {{- with .Values.podSecurityContext }}
          {{- . | toYaml | nindent 8 }}
        {{- end }}
      nodeSelector:
        kubernetes.io/os: linux
      affinity:
        nodeAffinity:
{{ toYaml .Values.linux.nodeAffinity | indent 10 }}
      priorityClassName: system-node-critical
{{- with .Values.linux.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
      containers:
        - name: liveness-probe
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
          image: "{{ .Values.image.baseRepo }}{{ .Values.image.livenessProbe.repository }}:{{ .Values.image.livenessProbe.tag }}"
          args:
            - --csi-address=/csi/csi.sock
            - --probe-timeout=3s
            - --health-port={{ .Values.node.livenessProbe.healthPort }}
            - --v=2
          resources: {{- toYaml .Values.linux.resources.livenessProbe | nindent 12 }}
          securityContext:
            {{- with .Values.securityContext.node }}
              {{- . | toYaml | nindent 12 }}
            {{- end }}
        - name: node-driver-registrar
          image: "{{ .Values.image.baseRepo }}{{ .Values.image.nodeDriverRegistrar.repository }}:{{ .Values.image.nodeDriverRegistrar.tag }}"
          args:
            - --csi-address=$(ADDRESS)
            - --kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)
            - --v=2
          livenessProbe:
            exec:
              command:
                - /csi-node-driver-registrar
                - --kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)
                - --mode=kubelet-registration-probe
            initialDelaySeconds: 30
            timeoutSeconds: 15
          env:
            - name: ADDRESS
              value: /csi/csi.sock
            - name: DRIVER_REG_SOCK_PATH
              value: {{ .Values.linux.kubelet }}/plugins/{{ .Values.driver.name }}/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
            - name: registration-dir
              mountPath: /registration
          resources: {{- toYaml .Values.linux.resources.nodeDriverRegistrar | nindent 12 }}
          securityContext:
            {{- with .Values.securityContext.node }}
              {{- . | toYaml | nindent 12 }}
            {{- end }}
        - name: azuredisk
          image: "{{ .Values.image.baseRepo }}{{ .Values.image.azuredisk.repository }}:{{ .Values.image.azuredisk.tag }}"
          args:
            - "--v={{ .Values.node.logLevel }}"
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--nodeid=$(KUBE_NODE_NAME)"
            - "--metrics-address=0.0.0.0:{{ .Values.node.metricsPort }}"
            - "--enable-perf-optimization={{ .Values.linux.enablePerfOptimization }}"
            - "--drivername={{ .Values.driver.name }}"
            - "--volume-attach-limit={{ .Values.driver.volumeAttachLimit }}"
            - "--cloud-config-secret-name={{ .Values.node.cloudConfigSecretName }}"
            - "--cloud-config-secret-namespace={{ .Values.node.cloudConfigSecretNamespace }}"
            - "--custom-user-agent={{ .Values.driver.customUserAgent }}"
            - "--user-agent-suffix={{ .Values.driver.userAgentSuffix }}"
            - "--allow-empty-cloud-config={{ .Values.node.allowEmptyCloudConfig }}"
            - "--support-zone=true"
            - "--get-node-info-from-labels=false"
          ports:
            - containerPort: {{ .Values.node.livenessProbe.healthPort }}
              name: healthz
              protocol: TCP
          livenessProbe:
            failureThreshold: 5
            httpGet:
              path: /healthz
              port: healthz
            initialDelaySeconds: 30
            timeoutSeconds: 10
            periodSeconds: 30
          env:
            - name: AZURE_CREDENTIAL_FILE
              value: {{ .Values.linux.azure_credential_file }}
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
            {{- if and $proxy.noProxy $proxy.http $proxy.https }}
            - name: NO_PROXY
              value: {{ $proxy.noProxy }}
            - name: no_proxy
              value: {{ $proxy.noProxy }}
            - name: HTTP_PROXY
              value: {{ $proxy.http }}
            - name: http_proxy
              value: {{ $proxy.http }}
            - name: HTTPS_PROXY
              value: {{ $proxy.https }}
            - name: https_proxy
              value: {{ $proxy.https }}
            {{- end }}
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          imagePullPolicy: {{ .Values.image.azuredisk.pullPolicy }}
          securityContext:
            {{- with .Values.securityContext.node }}
              {{- . | toYaml | nindent 12 }}
            {{- end }}
            privileged: true
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
            - mountPath: {{ .Values.linux.kubelet }}/
              mountPropagation: Bidirectional
              name: mountpoint-dir
            - mountPath: /etc/kubernetes/
              name: azure-cred
            - mountPath: /dev
              name: device-dir
            - mountPath: /sys/bus/scsi/devices
              name: sys-devices-dir
            - mountPath: /sys/class/
              name: sys-class
          resources: {{- toYaml .Values.linux.resources.azuredisk | nindent 12 }}
      volumes:
        - hostPath:
            path: {{ .Values.linux.kubelet }}/plugins/{{ .Values.driver.name }}
            type: DirectoryOrCreate
          name: socket-dir
        - hostPath:
            path: {{ .Values.linux.kubelet }}/
            type: DirectoryOrCreate
          name: mountpoint-dir
        - hostPath:
            path: {{ .Values.linux.kubelet }}/plugins_registry/
            type: DirectoryOrCreate
          name: registration-dir
        - hostPath:
            path: /etc/kubernetes/
            type: DirectoryOrCreate
          name: azure-cred
        - hostPath:
            path: /dev
            type: Directory
          name: device-dir
        - hostPath:
            path: /sys/bus/scsi/devices
            type: Directory
          name: sys-devices-dir
        - hostPath:
            path: /sys/class/
            type: Directory
          name: sys-class

{{- end }}
