{{ if .Values.snapshot.verticalPodAutoscaler.enabled }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ .Values.snapshot.snapshotController.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.snapshot.snapshotController.name }}
    app.kubernetes.io/component: "snapshotController"
{{ include "azuredisk.labels" . | indent 4 }}
spec:
  resourcePolicy:
    containerPolicies:
    - containerName: {{ .Values.snapshot.snapshotController.name }}
      controlledValues: RequestsAndLimits
      mode: Auto
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name:  {{ .Values.snapshot.snapshotController.name }}
  updatePolicy:
    updateMode: Auto
{{ end }}
