{{- if .Values.snapshot.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "azuredisk.name.crdInstall" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook-weight": "-5"
    {{- include "annotations.CRDInstall" . | nindent 4 }}
  labels:
    app.kubernetes.io/component: "{{ template "azuredisk.name.crdInstall" . }}"
    {{- include "azuredisk.labels" . | nindent 4 }}
    role: "{{ template "azuredisk.CRDInstallSelector" . }}"
{{- end }}
